version: '3'
services:
  spring-demo:
    build:
      context: .
      dockerfile: main.Dockerfile
    ports:
      - "82:8080"
    networks:
      - demo-compose-network
    depends_on:
      - mysql-db
  mysql-db:
    container_name: db_mysql
    build:
      context: .
      dockerfile: mysql.Dockerfile
    networks:
      - demo-compose-network
    volumes:
      - mysql-data:/var/lib/mysql
  session:
    image: redis
    networks:
      - demo-compose-network
volumes:
  mysql-data:
networks:
  demo-compose-network:
    driver: bridge
