version: '3'
services:
  spring-demo:
    build:
      context: .
      dockerfile: main.Dockerfile
    image: spring-demo
    ports:
      - "82:8080"
    networks:
      - demo-compose-network
    depends_on:
      - db-mysql
    restart: always
  db-mysql:
    container_name: db-mysql
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: db-mysql
    ports:
      - "3306"
    networks:
      - demo-compose-network
    volumes:
      - mysql-data:/var/lib/mysql
  session:
    image: redis
    networks:
      - demo-compose-network
volumes:
  mysql-data:
networks:
  demo-compose-network:
    driver: bridge
