apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.sample.yml --out ./.k8s/
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-mysql
  name: db-mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: db-mysql
status:
  loadBalancer: {}
