apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.sample.yml --out ./.k8s/
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spring-demo
  name: spring-demo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spring-demo
    spec:
      containers:
      - image: spring-demo
        name: spring-demo
        ports:
        - containerPort: 8080
        resources: {}
        imagePullPolicy: Never
      restartPolicy: Always
status: {}
