apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.sample.yml --out ./.k8s/
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spring-demo
  name: spring-demo
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
    nodePort: 32000
    protocol: tcp
  selector:
    io.kompose.service: spring-demo
  type:
    NodePort
status:
  loadBalancer: {}
